routes/web.php
<?php

Route::get('/', function () {
    return view('index');
});

Route::get('/ödeme',function(){
    return view('ödeme');
});

Route::get('/onay',function(){
    return view('onay');
});

Route::get('/blog-detay',function(){
    return view('blog-detay');
});

Route::get('/detay',function(){
    return view('detay');
});

Route::get('/admin-bookings',function(){
    return view('admin-bookings');
});

Route::get('/blog-olusturma',function(){
    return view('blog-olusturma');
});

Route::get('/admin-profile',function(){
    return view('admin-profile');
});

Route::get('/danisan-giris',function(){
    return view('danisan-giris');
});

Route::get('/yonetici-giris',function(){
    return view('yonetici-giris');
});

Route::get('/danisan-edit',function(){
    return view('danisan-edit');
});

Route::get('/danisan-messages',function(){
    return view('danisan-messages');
});

Route::get('/danisan-olculeri',function(){
    return view('danisan-olculeri');
});

Route::get('/yonetim-onay',function(){
    return view('yonetim-onay');
});


Route::get('/onayla/{id}','YonetimController@onayla');

Route::get('/yonetim-onay','YonetimController@onay');

Route::get('/yonetim-mesajlar','YonetimController@yonetim_mesajlar');

Route::get('/admin-index','DiyetisyenController@adminIndex');

Route::get('/admin-messages','DiyetisyenController@adminMessages');

Route::get('/danisan-messages','DanisanController@danisanMessages');

Route::get('/mesajAl','DiyetisyenController@mesajAl');

Route::get('/admin-profile','DiyetisyenController@edit');

Route::get('/danisan-edit','DanisanController@edit');

Route::get('/cikis','DiyetisyenController@logout');

Route::get('/danisan_cikis','DanisanController@danisan_logout');

Route::get('/yonetici_cikis','YonetimController@yonetici_logout');

Route::get('/danisan-profile','DanisanController@danisanProfile');

Route::post('/login','DiyetisyenController@login');

Route::post('/mesajGonder','HomeController@mesajGonder');

Route::post('/yonetici_login','YonetimController@yonetici_login');

Route::post('/olcuduzenle','DanisanController@olcuduzenle');

Route::post('/sirala','DiyetisyenController@sirala');

Route::post('/danisan_login','DanisanController@danisan_login');

Route::resource('diyetisyens','DiyetisyenController');

Route::resource('danisans','DanisanController');

Route::resource('blogs','BlogController');

Route::resource('yorums','YorumController');

Route::resource('odemes','OdemeController');

Route::get('admin-blogs','BlogController@adminBlogs');

Route::post('blog-ara','BlogController@ara');

Route::post('diyetisyen-ara','DiyetisyenController@ara');

Route::get('index','HomeController@index');

Route::get('iletisim','HomeController@iletisim');

Route::get('sss','HomeController@sss');

Route::get('giris','HomeController@giris');

Route::get('diyetisyen-kayit','HomeController@diyetisyenkayit');

Route::get('danisan-kayit','HomeController@danisankayit');

Route::resource('messages','MessageController');

resources/views/admin-blogs.blade.php
@extends('layouts.admin-layout')

@section('content')
    <!-- /Navigation-->
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/admin-index">Panel</a>
        </li>
        <li class="breadcrumb-item active">Bloglarım</li>
      </ol>
		<!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Bloglarım 
          <a href="{{URL('blogs/create')}}"><button style="float:right;" class="btn btn-primary">Blog Oluştur</button></a>
        </div>
          <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Başlık</th>
                  <th>İçerik</th>
                  <th>Resim</th>
                  <th>Oluşturma Tarihi</th>
                  <th>Düzenle</th>
                  <th>Sil</th>
                </tr>
              </thead>
              <tbody>

                @foreach($bloglar as $blog)
                <tr>
                  <td>{{$blog->baslik}}</td>
                  <td>{!! str_limit($blog->icerik, $limit = 250, $end = '...') !!}</td>
                  <td><img width="100px" src="uploads/{{$blog->resim}}"></td>
                  <td>{{$blog->created_at}}</td>
                <td> <a class="btn btn-success" href="{{ route('blogs.edit', $blog->slug) }}">Düzenle</a></td>
                <td>
                  {!! Form::open(['action' => ['BlogController@destroy' , $blog->id] , 'method' => 'POST' , 'class' => 'pull-right' ]) !!}
                  {{ Form::hidden('_method' , 'DELETE') }}
                  {{ Form::submit('Sil' , ['class' => 'btn btn-danger'])}}
                  {!! Form::close() !!}
                </td>
                </tr>
                @endforeach

              </tbody>
            </table>
            {{ $bloglar->links() }}
          </div>
        </div>
      </div>
	  <!-- /tables-->
	  </div>
	  <!-- /container-fluid-->
   	</div>
@endsection

resources/views/admin-messages.blade.php
@extends('layouts.admin-layout')

@section('content')

<div class="content-wrapper">
    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="/admin-index">Panel</a>
        </li>
        <li class="breadcrumb-item active">Mesajlar</li>
        </ol>
        <div class="box_general">
            <h4>Mesaj Listesi</h4>
            <?php
                if(isset($_SESSION['diyetisyen']))
                {
                    $email = $_SESSION['diyetisyen'];
                    $user = DB::table('diyetisyens')->where('email',$_SESSION['diyetisyen'])->first();
                    $danisans = DB::table('danisans')->where('diyetisyen_id',$user->id)->paginate(5);
                    $message_count = 0;
                }
            ?>
            <div class="list_general">
                <ul>
                    @foreach($danisans as $danisan)
                    <?php
                        $message = DB::table('messages')
                        ->where([
                            ['sender_id', '=', $user->id],
                            ['receiver_id', '=', $danisan->id],
                        ])
                        ->orWhere([
                            ['receiver_id', '=', $user->id],
                            ['sender_id', '=', $danisan->id],
                        ])
                        ->latest('id')->first();

                        if($message)
                            $message_count++;
                    ?>
                        @if($message)
                        <li class="message-item">
                            <a href="{{ route('messages.show', $danisan->id) }}">
                                <span>{{ $message->created_at }}</span>
                                <figure><img src="/uploads/{{$danisan->p_foto}}" alt=""></figure>
                                <h4>{{$danisan->ad}} {{$danisan->soyad}}</h4>
                                <p>{{ $message->content }}</p>
                            </a>
                        </li>
                        @endif
                    @endforeach
                        @if($message_count == 0)
                            <li style="padding-left: 30px;padding-top: 15px; padding-bottom: 15px">
                                Herhangi bir mesajınız bulunmamaktadır.
                            </li>
                        @else
                        {{ $danisans->links() }}
                        @endif
                </ul>
            </div>
        </div>
    
        <!-- /box_general-->
        </div>
        <!-- /container-fluid-->
        </div>
    <!-- /container-wrapper-->

    @endsection

resources/views/blog-detay.blade.php
@extends('layouts.layout')

@section('title')
Blog Detay Sayfası
@endsection

@section('content')
<main>
		<div id="breadcrumb">
			<div class="container">
				<ul>
					<li><a href="/index">Anasayfa</a></li>
					<li><a href="/blogs">Bloglar</a></li>
					<li>{{$detay->baslik}}</li>
				</ul>
			</div>
		</div>
		<!-- /breadcrumb -->
		
		<div class="container margin_60">
			<div class="row">
				<div class="col-lg-9">
					<div class="bloglist singlepost">
						<p><img class="img-fluid" src="/uploads/{{$detay->resim}}"></p>
						<h1>{{$detay->baslik}}</h1>
						<div class="postmeta">
							<ul>
								<li><i class="icon_clock_alt"></i> Yayın Tarihi: {{$detay->created_at}}</li>
								<li><a href="/diyetisyens/{{$detay->diyetisyen->slug}}"><i class="icon_pencil-edit"></i> {{$detay->diyetisyen->ad}} {{$detay->diyetisyen->soyad}}</a></li>
								<li><a href="#comments"><i class="icon_comment_alt"></i> ({{count($detay->yorumlar)}}) Yorum</a></li>
								<li><i class="fa fa-eye"></i> {{$detay->visit_count}}</li>
							</ul>
						</div>
						<!-- /post meta -->
						<div class="post-content">
							<div class="dropcaps">
								{!! $detay->icerik !!}
							</div>
						</div>
						<!-- /post -->
					</div>
					<!-- /single-post -->
					<?php
						$id = $detay->id;
					?>

					<div id="comments">
						@if(isset($_SESSION['danisan']))
						<h5>Yorum Ekle</h5>

						@include('common.errors')

						{!! Form::open(['action' => ['YorumController@store', $id], 'method' => 'POST']) !!}
							<div class="form-group">
								{{ Form::textarea('Yorum',null,['class'=>'form-control', 'rows' => 6, 'cols' => 40, 'placeholder' => 'Yorumunuzu Giriniz']) }}
							</div>
							<div class="form-group">
							<input type="hidden" name="blog_id" value="<?php echo $id; ?>" />
							{{ Form::submit('Yorum Ekle',['class' => 'btn_1']) }}
							</div>
						{!! Form::close() !!}
						@endif
						<hr>
						<?php use App\Danisan; ?>
						<h5>Yorumlar ({{count($detay->yorumlar)}})</h5>
						<ul>

							@foreach ($detay->yorumlar as $yorum)

							<?php 
								$user = Danisan::find($yorum->danisan_id);	
							?>
							<li>
								<div class="avatar">
									<a href="#"><img src="/uploads/{{$user->p_foto}}" alt="">
									</a>
								</div>
								<div class="comment_right clearfix">
									<div class="comment_info">
										Yorum Sahibi: <b>{{$user->ad}} {{$user->soyad}}</b><span>|</span>{{$yorum->created_at}}<span>
									</div>
									<p>
										{{$yorum->icerik}}
									</p>
								</div>
							</li>

							@endforeach
						</ul>
					</div>
				</div>
				<!-- /col -->
				
				<aside class="col-lg-3">
					<div class="widget">
						
							@include('common.errors')

							{!! Form::open(['action' => 'BlogController@ara' , 'method' => 'POST']) !!}
								<div class="form-group">
									{{Form::text('Arama',isset($search) ? $arama : null,['class' => 'form-control' , 'placeholder' => 'Arama kelimesi giriniz.'])}}
								</div>
								{{Form::submit('Ara',['class' => 'btn_1 btn_md'])}}
							{!! Form::close() !!}
						</div>
						<!-- /widget -->
		
						<div class="widget">
							<div class="widget-title">
								<h4>Yeni Bloglar</h4>
							</div>
							<ul class="comments-list">
								@foreach($recents as $post)
									<li>
										<div class="alignleft">
											<a href="{{ route('blogs.show', $post->id) }}"><img src="/uploads/{{$post->resim}}" alt=""></a>
										</div>
										<small>{{$post->created_at}}</small>
										<h3><a href="{{ route('blogs.show', $post->id) }}" title="">{!! str_limit($post->icerik, $limit = 40, $end = '...') !!}</a></h3>
									</li>
								@endforeach
							</ul>
						</div>
						<!-- /widget -->
				</aside>
				<!-- /aside -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
</main>
	<!-- /main -->
@endsection

resources/views/blog.blade.php
@extends('layouts.layout')

@section('title')
Bloglar Sayfası
@endsection

@section('content')
<main>
    <div id="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="/index">Anasayfa</a></li>
                <li>Bloglar</li>
            </ul>
        </div>
    </div>
    <!-- /breadcrumb -->

    <div class="container margin_60">
        <div class="main_title">
                @if(isset($search))
                <h1>
                    Aradığınız Kelime: {{$arama}}
                </h1>
                <p>{{count($blogs)}} Sonuç Bulundu.</p>
                @else
                <h1>
                    Blog Yazılarımız
                </h1>
                <p>Uzman diyetisyenlerin çeşitli konular hakkındaki blogları</p>
                @endif
        </div>
        <div class="row">
            <div class="col-lg-9">
                @foreach($blogs as $blog)
                <article class="blog wow fadeIn">
                    <div class="row no-gutters">
                        <div class="col-lg-7">
                            <figure>
                                <a href="{{ route('blogs.show', $blog->slug) }}"><img src="uploads/{{$blog->resim}}" alt=""><div class="preview"><span>Devamını Göster</span></div></a>
                            </figure>
                        </div>
                        <div class="col-lg-5">
                            <div class="post_info">
                                <small>{{$blog->created_at->format('d/m/Y')}}</small>
                                <h3><a href="{{ route('blogs.show', $blog->slug) }}">{{$blog->baslik}}</a></h3>
                                {!! str_limit($blog->icerik, $limit = 250, $end = '...') !!}
                                <ul>
                                    <li>
                                        <div class="thumb"><img src="uploads/{{$blog->diyetisyen->p_foto}}" alt=""></div> {{$blog->diyetisyen->ad}} {{$blog->diyetisyen->soyad}}
                                    </li>
                                    <li style="padding-left: 115px; padding-right: 0"><i class="fa fa-eye" aria-hidden="true"></i> {{$blog->visit_count}}</li>
                                    <li><i style="vertical-align: top; display: inline-block; margin-top: 2px" class="icon_comment_alt"></i> {{count($blog->yorumlar)}} </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </article>
                @endforeach
                
            </div>
            <!-- /col -->
            
            <aside class="col-lg-3">
                <div class="widget">

                    @include('common.errors')
                        
                    {!! Form::open(['action' => 'BlogController@ara' , 'method' => 'POST']) !!}
                        <div class="form-group">
                            {{Form::text('Arama',isset($search) ? $arama : null,['class' => 'form-control' , 'placeholder' => 'Arama kelimesi giriniz.'])}}
                        </div>
                        {{Form::submit('Ara',['class' => 'btn_1 btn_md'])}}
                    {!! Form::close() !!}
                </div>
                <!-- /widget -->

                <div class="widget">
                    <div class="widget-title">
                        <h4>Yeni Bloglar</h4>
                    </div>
                    <ul class="comments-list">
                        @foreach($recents as $post)
                            <li>
                                <div class="alignleft">
                                    <a href="{{ route('blogs.show', $post->slug) }}"><img src="/uploads/{{$post->resim}}" alt=""></a>
                                </div>
                                <small>{{$post->created_at}}</small>
                                <h3><a href="{{ route('blogs.show', $post->slug) }}" title="">{!! str_limit($post->icerik, $limit = 40, $end = '...') !!}</a></h3>
                            </li>
                        @endforeach
                    </ul>
                </div>
                <!-- /widget -->
                
            </aside>
            <!-- /aside -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</main>
<!-- /main -->
@endsection

resources/views/danisan-edit.blade.php
@extends('layouts.danisan-admin-layout')

@section('content')

<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Panel</a>
        </li>
        <li class="breadcrumb-item active">Profil Düzenleme</li>
      </ol>
		<div class="box_general padding_bottom">
			<div class="header_box version_2">
				<h2><i class="fa fa-user"></i>Profilini Düzenleyin</h2>
			</div>

			@include('common.errors')
			
			{!! Form::open(['action' => ['DanisanController@update' , $danisan->id], 'method' => 'POST', 'files'=>'true' ]) !!}
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label>Adınız</label>
							{{Form::text('Ad',$danisan->ad ,['class' => 'form-control' , 'placeholder' => 'Adınızı Giriniz'])}}
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label>Soyadınız</label>
							{{Form::text('Soyad',$danisan->soyad ,['class' => 'form-control' , 'placeholder' => 'Soyadınızı Giriniz'])}}
					</div>
					</div>
				</div>
				<!-- /row-->
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<label>Email Adresi</label>
							{{Form::text('Email',$danisan->email ,['class' => 'form-control' , 'placeholder' => 'Email Adresinizi Giriniz'])}}	
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<label>Boy</label>
							{{Form::text('Boy',$danisan->boy ,['class' => 'form-control' , 'placeholder' => 'Boyunuzu Giriniz'])}}
						</div>
					</div>
				</div>
				<!-- /row-->
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<label>Profil Fotoğrafınız</label>
							@if(!empty($danisan->p_foto))
								<img style="width: 100px; display: block; margin-bottom: 10px" src="/uploads/{{ $danisan->p_foto }}"/>
							@endif
							{{ Form::file('Profil',null)}}
						</div>
					</div>
				</div>
		</div>

			<div class="row">
				<div class="col-md-12">
					<div class="box_general padding_bottom">
						<div class="header_box version_2">
							<h2><i class="fa fa-lock"></i>Şifre Değiştirme</h2>
						</div>
						<div class="form-group">
							<label>Eski Şifre</label>
							{{Form::password('E_Sifre',['class' => 'form-control' , 'placeholder' => ''])}}
						</div>
						<div class="form-group">
							<label>Yeni Şifre</label>
							{{Form::password('Y_Sifre',['class' => 'form-control' , 'placeholder' => ''])}}
						</div>
						<div class="form-group">
							<label>Yeni Şifre Tekrar</label>
							{{Form::password('TY_Sifre',['class' => 'form-control' , 'placeholder' => ''])}}
						</div>
					</div>
				</div>			
			</div>

		{{Form::hidden('_method','PUT')}}
		<p>  {{Form::submit('Profilimi Düzenle',['class' => 'btn_1 medium'])}} </p>
			{!! Form::close() !!}
		</div>

		<!-- /box_general-->
		
		<!-- /row-->
		
		
	  </div>
	  <!-- /.container-fluid-->
   	</div>
	<!-- /.container-wrapper-->

@endsection

resources/views/danisan-messages.blade.php
@extends('layouts.danisan-admin-layout')

@section('content')


<div class="content-wrapper">
    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="/danisan-profile">Panel</a>
        </li>
        <li class="breadcrumb-item active">Mesajlar</li>
        </ol>
        <div class="box_general">
            <h4>Mesaj Listesi</h4>
            <?php
                if(isset($_SESSION['danisan']))
                {
                    $email = $_SESSION['danisan'];
                    $user = DB::table('danisans')->where('email',$email)->first();
                    $message_count = 0;
                }
            ?>
            <div class="list_general">
                <ul>
                    @foreach($diyetisyens as $diyetisyen)
                    <?php
                        $message = DB::table('messages')
                        ->where([
                            ['sender_id', '=', $user->id],
                            ['receiver_id', '=', $diyetisyen->id],
                        ])
                        ->orWhere([
                            ['receiver_id', '=', $user->id],
                            ['sender_id', '=', $diyetisyen->id],
                        ])
                        ->latest('id')->first();
                            if($message)
                                $message_count++;
                    ?>
                        @if($message)
                        <li class="message-item">
                        <a href="{{ route('messages.show', $diyetisyen->id) }}">
                                <span>{{ $message->created_at }}</span>
                                <figure><img src="/uploads/{{$diyetisyen->p_foto}}" alt=""></figure>
                                <h4>{{$diyetisyen->ad}} {{$diyetisyen->soyad}}</h4>
                                <p>{{ $message->content }}</p>
                            </a>
                        </li>
                        @endif
                    @endforeach
                    @if($message_count == 0)
                    <li style="padding-left: 30px;padding-top: 15px; padding-bottom: 15px">
                            Herhangi bir mesajınız bulunmamaktadır.
                    </li>
                    @endif
                </ul>
            </div>
        </div>
    
    </div>
        <!-- /container-fluid-->
</div>
    <!-- /container-wrapper-->
@endsection

resources/views/danisan-profile.blade.php
<?php
  use App\VucutOlcusu;
  use App\Odeme;
  
  $item = VucutOlcusu::where('danisan_id',$danisan->id)->latest('id')->first();

    if(isset($item))
    {
        $vki  = $item->kilo / pow($danisan->boy/100,2);
    }

  $hizmet = Odeme::where("danisan_id", $danisan->id)->latest("id")->first();
  
    if(isset($hizmet))
    {
        $bitis_tarihi = strtotime($hizmet->bitis_tarihi) - time();
        $bitis_tarihi = floor($bitis_tarihi / (60*60*24) );
    }
?>
@extends('layouts.danisan-admin-layout')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
        <a href="#">Hoşgeldiniz {{ $danisan->ad }} {{ $danisan->soyad }}</a>
        </li>
        <li class="breadcrumb-item active">Panel</li>
      </ol>
	  <!-- Icon Cards-->
      <div class="row">
        <div class="col-xl-4 col-sm-6 mb-3">
          <div class="card dashboard text-white bg-primary o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-user-md"></i>
              </div>
                @if( isset($danisan->diyetisyen->id) )
                <div class="mr-5"><h5>Diyetisyeniniz:<br> {{ $danisan->diyetisyen->ad }} {{ $danisan->diyetisyen->soyad }}</h5></div>
                @else
                <div class="mr-5"><h5>Diyetisyeniniz bulunmamaktadır.</h5></div>
                @endif
            </div>
                @if( isset($danisan->diyetisyen->id) )
                <a class="card-footer text-white clearfix small z-1" href="{{ route('messages.show', $danisan->diyetisyen->id) }}">
                  <span class="float-left">Mesaj Gönderin</span>
                  <span class="float-right">
                    <i class="fa fa-angle-right"></i>
                  </span>
                </a>
                @else
                <a class="card-footer text-white clearfix small z-1" href="{{ URL('diyetisyens') }}">
                  <span class="float-left">Diyetisyenlere Göz Atın</span>
                  <span class="float-right">
                    <i class="fa fa-angle-right"></i>
                  </span>
                </a>
                @endif
          </div>
        </div>
        <div class="col-xl-4 col-sm-6 mb-3">
          <div class="card dashboard text-white bg-warning o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-check"></i>
              </div>
              @if(isset($vki))
              <div class="mr-5"><h5>Vücut Kitle İndeksiniz:<br>
              {{ number_format($vki, 2) }}
              @else
              <div class="mr-5"><h5>Vücut Kitle İndeksinizi Hesaplamak İçin Ölçülerinizi Giriniz.<br>
              @endif
            </h5>
            </div>
            </div>
            <span class="card-footer text-white clearfix small z-1">
              <span class="float-left">
                @if(isset($vki))
                  @if($vki <= 18.8)
                  Zayıf
                  @elseif($vki > 18.8 && $vki < 25)
                  Normal
                  @elseif($vki > 25 && $vki < 30)
                  Hafif Kilolu
                  @elseif($vki >= 30)
                  Obez
                  @endif
                @else
                  <a style="color: #fff !important" href="{{ URL('danisan-olculeri') }}">Ölçülerime Git</a>
                @endif
              </span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </span>
          </div>
        </div>
        @if( isset($danisan->diyetisyen->id) )
        <div class="col-xl-4 col-sm-6 mb-3">
          <div class="card dashboard text-white bg-success o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-calendar-times-o"></i>
              </div>
              <div class="mr-5"><h5>Hizmet Sürenizin Bitmesine <b>{{$bitis_tarihi}}</b> Gün Kaldı.</h5></div>
            </div>
          </div>
        </div>
        @endif
		</div>
		<!-- /cards -->
		<h2></h2>
      <div class="box_general padding_bottom">
        <div class="header_box version_2">
          <h2><i class="fa fa-bar-chart"></i>Kilo Değişimi</h2>
        </div>
      <canvas id="myAreaChart" width="100%" height="30" style="margin:45px 0 15px 0;"></canvas>
      </div>
	   </div>
	  <!-- /.container-fluid-->
    </div>
       
@endsection

resources/views/diyetisyenler.blade.php
<?php 

	$tip = isset($type) ? $type : null;

?>

@extends('layouts.layout')

@section('title')
Diyetisyenler Sayfası
@endsection

@section('content')
<main class="theia-exception">
		<div id="results">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
					<h4>{{ count($lists) }} sonuç listelendi.</h4>
					</div> 
					<div class="col-md-6">
						
							@include('common.errors')

						{!! Form::open(['action' => 'DiyetisyenController@ara' , 'method' => 'POST']) !!}	
							<div class="search_bar_list">
								{{Form::text('Arama',isset($search) ? $arama : null,['class' => 'form-control' , 'placeholder' => 'Diyetisyen (Başak Öztürk)...'])}}
							
								{{Form::submit('Ara')}}
								</div>
							
						{!! Form::close() !!}
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /results -->

		<div class="filters_listing">
			<div class="container">
				<ul class="clearfix">
					<li>
						<h6>Sırala</h6>
						{!! Form::open(['action' => 'DiyetisyenController@sirala' , 'method' => 'POST']) !!}
							<select class="my-select" value="{{ $tip }}" name="orderby" class="selectbox" onchange="this.form.submit()">
								<option <?php echo $tip == "puan" ? "selected" : "" ?> value="puan">Puan</option>
								<option <?php echo $tip == "hizmet" ? "selected" : "" ?> value="hizmet">Hizmet Sayısı</option>
							</select>
						{!! Form::close() !!}
					</li>
				</ul>
			</div>
			<!-- /container -->
		</div>
		<!-- /filters -->
		
		<div class="container" style="padding: 20px 15px">
			<div class="row">
				<div class="col-lg-12">
					@if(count($lists) > 0)
						@foreach($lists as $list)
						<div class="strip_list wow fadeIn">
							{{-- <a href="#0" class="wish_bt"></a> --}}
							<figure>
							<img src="/uploads/{{$list->p_foto}}" alt="">
							</figure>
							<h3><a href="{{ route('diyetisyens.show', $list->slug) }}">{{$list->ad}} {{$list->soyad}}</a></h3>
			
							<p>{{ str_limit($list->bio, $limit = 250, $end = '...') }}</p>
						
							<span class="rating">
								@for($i = 0; $i < 5; $i++)
									@if($i < ceil($list->puan))
										<i class="icon_star voted"></i>
									@else
										<i class="icon_star"></i>
									@endif
								@endfor
								<small>{{$list->puan}}</small></span>
							<ul>
								<li></li>
								<li><a href="{{ route('diyetisyens.show', $list->slug) }}">Diyete Başla</a></li>
							</ul>
						</div>
						@endforeach
						
						{{$lists->links()}}
					@else
						<h2 style="text-align: center; margin-bottom: 30px">
							"{{$arama}}" kelimesine uygun diyetisyen bulunamadı. 
						</h2>
					@endif
					
					
				</div>
				<!-- /col -->
			
				
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</main>
	<!-- /main -->
   @endsection